<?php

/**
 * @file
 * Contains dam_content.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
// Required as of the 2.x branch.
use Drupal\realistic_dummy_content_api\includes\RealisticDummyContentRecipe;

/**
 * Implements hook_help().
 */
function dam_content_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dam_content module.
    case 'help.page.dam_content':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Test content for DAM Project.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function dam_content_theme() {
  return [
    'dam_content' => [
      'render element' => 'children',
    ],
  ];
}


/**
 * An example recipe. This one creates four pages, and then 10 articles.
 */
// @codingStandardsIgnoreStart
// We cannot Make this file conform to coding standards because existing
// projects might have used this as an example and we need to continue
// supporting this technique for defining recipes.
class dam_realistic_dummy_content_recipe extends RealisticDummyContentRecipe {

  /**
   * {@inheritdoc}
   */
  public function _Run_() {
    // If you want sequential numbering rather than random numbering, use
    // variable_set('realistic_dummy_content_api_rand',
    // REALISTIC_DUMMY_CONTENT_API_SEQUENTIAL);.


    // $this->NewEntities('node', 'page', 4, array('kill' => TRUE));
    $this->NewEntities('node', 'article', 10, array('kill' => TRUE));
  }
  // @codingStandardsIgnoreEnd

}
