<?php

/**
 * @file
 * Install and uninstall functions for the communications_person module.
 */
use Drupal\node\Entity\Node;
use Drupal\file\Entity\File;
use Drupal\media_entity\Entity\Media;
use Drupal\media_entity\MediaInterface;
use Drupal\Component\Utility\Random;
use Drupal\menu_link_content\Entity\MenuLinkContent;

use Drupal\Component\Plugin\PluginBase;
use Drupal\Core\Config\Config;
use Drupal\Core\Entity\EntityFieldManagerInterface;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Core\StringTranslation\StringTranslationTrait;
use Drupal\Core\Plugin\ContainerFactoryPluginInterface;
use Drupal\Component\Utility\NestedArray;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\taxonomy\Entity\Term;

use Drupal\communications\Entity\Term;
use Drupal\communications\TaxonomyTermCreate as TermBuild;

/**
 * Implements hook_install().
 */
function dam_content_install() {
  // To create a new media entity:
  $entity_type_manager = \Drupal::service('entity_type.manager');
  $bundle = $entity_type_manager
          ->getStorage('media_bundle')
          ->loadByProperties(['type' => 'image']);

  $i = 1;
  while ($i <= 30) {
    $stock_image = \Drupal::moduleHandler()->getModule('dam_content')->getPath() . "/images/$i.jpg";
    $filesystem = \Drupal::service('file_system');
    $destination = file_unmanaged_copy($stock_image, 'public://' . $filesystem->basename($stock_image));

    if ($destination) {
      // Create file entity.
      $file = File::create();
      $file->setFileUri($destination);
      $file->setOwnerId(\Drupal::currentUser()->id());
      $file->setMimeType('image/' . pathinfo($destination, PATHINFO_EXTENSION));
      $file->setFileName($filesystem->basename($destination));
      $file->setPermanent();
      $file->save();

      // Create media entity and save.
      $media_image = $entity_type_manager->getStorage('media')->create([
                       'bundle' => 'image',
                       $bundle['image']->getTypeConfiguration()['source_field'] => $file,
                     ]);
      $media_image->save();
    }
    $i++;
  }

  $node = Node::create([
            'type' => 'page',
            'uid' => 1,
            'revision' => 0,
            'status' => TRUE,
            'promote' => 0,
            'created' => time(),
            'langcode' => 'en',
            'title' => 'Help',
          ]);

  // $node->set('body', [
  //     'value' => '<h1>Welcome to My Page!</h1>',
  //     'format' => 'basic_html'
  //   ]);

  $random = new Drupal\Component\Utility\Random();
  $node->set('body', $random->paragraphs(6));
  $node->save();

  $source = '/node/' . $node->get('nid')->value;
  \Drupal::service('path.alias_storage')->save($source, '/help', 'en');


  // $destination = 'public://my_module-images-2016';
  // file_prepare_directory($destination, FILE_CREATE_DIRECTORY);

  // $img_source = sprintf('%s/private/assets/testimg.jpg', \Drupal::root());
  // $img = null;

  // if (is_readable($img_source)) {
  //   $data = file_get_contents($img_source);

  //   $img = file_save_data(
  //     $data,
  //     $destination . '/testimg.jpg',
  //     FILE_EXISTS_REPLACE
  //   );
  // }

  //   if ($img) {
  //     $node->get('field_main_image')->appendItem($img);
  //   }

  // Navigation Menu Items
  $link = MenuLinkContent::create([
            'title'      => 'Help',
            'link'       => ['uri' => 'internal:/help'],
            'menu_name'  => 'main',
            'weight'     => 10,
          ]);
  $link->save();

  $tags = array(
      'basic sciences' => array(
          'biosciences' => array(
              'BioScreen C Instrument' => array(),
              'Fluorescence Activated Cell Sorter' => array(
                  'FACS' => array()),
              'genomics' => array(),
              'metabolomics' => array(),
              'proteomics' => array()),
          'characterization and measurement' => array(
              'analytical microscopy' => array(),
              'atomic force microscopy' => array(),
              'computational sciences' => array(
                  'high-performance?computing' => array(),
                  'visualization' => array()),
              'confocal laser scanning microscopy' => array(
                  'CLSM' => array()),
              'electrochemical characterization' => array(),
              'electron microscopy' => array(),
              'electron probe microanalyzer' => array(
                  'EPMA' => array()),
              'femtosecond laser spectroscopy' => array(),
              'Fourier transform infrared spectroscopy' => array(
                  'FTIR' => array()),
              'microscopy' => array(),
              'nanoscience' => array(),
              'near-field optical microscopes' => array(),
              'photoelectron spectroscopy' => array(),
              'raman spectroscopy' => array(),
              'scanning electron microscopy' => array(),
              'secondary ion mass spectrometry' => array(),
              'spectrometers' => array(),
              'spectroscopic scanning tunneling microscopy' => array(),
              'spectroscopy' => array(),
              'x-ray diffraction' => array(),
              'x-ray photoelectron spectroscopy' => array()),
          'chemicals and materials' => array(
              'aldehydes' => array(),
              'biodegradable plastics' => array(),
              'ceramics' => array(),
              'high temperature superconductors' => array(
                  'HTS' => array()),
              'photochemistry' => array(),
              'photoelectrochemistry' => array(),
              'silicon' => array(),
              'silicon carbide' => array(),
              'superconducting wires' => array(),
              'superconductivity' => array(),
              'thermochemistry' => array(),
              'vacuum insulation' => array())),
      'biomass and alternative fuels' => array(
          'feedstock' => array(
              'alfalfa' => array(),
              'corn' => array(
                  'stover' => array()),
              'crops' => array(),
              'RT: biofuels' => array(),
              'short rotation woody crops' => array(
                  'cottonwood' => array(),
                  'poplar' => array(),
                  'willow' => array()),
              'sugarcane' => array(
                  'bagasse' => array()),
              'switchgrass' => array(),
              'wood chips' => array()),
          'hydrogen and fuel cells' => array(
              'carbon nanotubes' => array(
                  'CNT' => array()),
              'hydrocarbon fuel cells' => array(),
              'methanol' => array(
                  'RT: biofuels' => array()),
              'photoelectrochemical cells' => array(),
              'photosynthesis' => array(),
              'proton exchange membranes' => array(
                  'PEM' => array())),
          'production and distribution' => array(
              'acid impregnator' => array(),
              'anaerobic digestion' => array(),
              'biodiesel' => array(
                  'RT: biofuels' => array()),
              'biorefinery' => array(),
              'compressed natural gas' => array(
                  'CNG' => array()),
              'digesters' => array(),
              'ethanol' => array(
                  'RT: biofuels' => array()),
              'fermenters' => array(),
              'gasification' => array(),
              'gasifiers' => array(),
              'heat exchangers' => array(),
              'liquefied natural gas' => array(
                  'LNG' => array()),
              'methane' => array(
                  'RT: biofuels' => array()),
              'methanol' => array(
                  'RT: biofuels' => array()),
              'natural gas' => array(),
              'phenols' => array(),
              'propane' => array(),
              'small modular biopower' => array(
                  'SMB' => array()),
              'Thermochemical Process Development Unit' => array(
                  'TCPDU' => array()),
              'wood gasification plants' => array(),
              'wood-burning power plants' => array()),
          'research' => array(
              'algae' => array(),
              'autoclave reactors' => array(),
              'biochemical conversion' => array(),
              'cellulase' => array(),
              'chromatography' => array(),
              'digesters' => array(),
              'electrostatic precipitators' => array(),
              'fluidized bed reactors' => array(),
              'fuels synthesis reactors' => array(),
              'gasification' => array(),
              'hydrolysis' => array(),
              'isothermal tubular reactors' => array(),
              'lignins' => array(),
              'lignocellulosics' => array(),
              'lipids' => array(),
              'methane' => array(
                  'RT: biofuels' => array()),
              'methanol' => array(
                  'RT: biofuels' => array()),
              'microalgae' => array(),
              'photosynthesis' => array(),
              'pretreatment reactor system' => array(),
              'pyrolysis' => array(),
              'thermochemical conversion' => array())),
      'building technologies' => array(
          'architecture and components' => array(
              'building materials' => array(),
              'Building Science Consortium' => array(),
              'building standards' => array(
                  'building codes' => array()),
              'building-integrated photovoltaics' => array(
                  'BIPV' => array()),
              'cellulose insulation' => array(),
              'concrete' => array(),
              'DOE Weatherization and Intergovernmental Program' => array(),
              'DOE Weatherization Assistance Program' => array(),
              'Earth sheltering' => array(),
              'Leadership in Energy and Environmental Design' => array(
                  'LEED' => array()),
              'lighting' => array(
                  'fluorescents' => array()),
              'materials' => array(),
              'photoelectrochemical cells' => array(),
              'photoelectrochromic windows' => array(
                  'smart glass' => array()),
              'reclaimed wood' => array(),
              'roofing' => array(),
              'shading' => array(),
              'spectrally selective glass' => array(),
              'Trombe Walls' => array(),
              'vacuum insulation' => array(),
              'walls' => array(),
              'weatherization' => array(),
              'windows' => array(),
              'wire mesh' => array(),
              'zero energy homes' => array(
                  'ZEH' => array())),
          'Greensburg, Kansas' => array(),
          'Habitat for Humanity' => array(),
          'zero energy homes' => array(
              'ZEH' => array()),
          'heating ventilation and air-conditioning' => array(
              'air conditioning' => array(),
              'desiccant-enhanced evaporative air conditioners' => array(
                  'DEVap' => array()),
              'ducts' => array(),
              'heat exchangers' => array(),
              'heat pump water heater' => array(),
              'heat pump water heaters' => array(
                  'HPWH' => array()),
              'heat pumps' => array(),
              'space heating' => array(),
              'transpired air collectors' => array(),
              'transpired solar collectors' => array(),
              'ventilation' => array(),
              'ventilation controllers' => array())),
      'commercialization and deployment' => array(
          'industry' => array(
              'manufacturing' => array()),
          'international' => array(
              'Village Power' => array()),
          'technology transfer' => array(),
          'Tribal Energy' => array(),
          'utilities' => array(
              'coal' => array(
                  'RT: fossil fuels' => array()),
              'fossil fuels' => array(
                  'RT: coal' => array(),
                  'RT: petroleum' => array()),
              'gasification' => array(),
              'net metering' => array(),
              'power lines' => array(),
              'power plants' => array(),
              'substations' => array(),
              'transmission towers' => array())),
      'corporate-education and events' => array(
          'American Solar Challenge' => array(
              'RT: Sunrayce' => array()),
          'awards' => array(
              'R & D 100' => array()),
          'Bike to Work Day' => array(),
          'conferences' => array(
              'Industry Growth Forum' => array(),
              'other conferences' => array(),
              'World Renewable Energy Forum' => array(
                  'WREF' => array())),
          'Continuum Magazine' => array(),
          'Earth Day' => array(),
          'Education - General' => array(
              'Coalition for Learning Opportunities and United Tutors Program' => array(
                  'CLOUT' => array()),
              'environmental fairs' => array(),
              'Expanding Your Horizons' => array(),
              'RnE2EW' => array(),
              'science camps' => array(),
              'Summer Science Adventures' => array(),
              'Take Our Sons and Daughters to Work Day' => array(),
              'tours' => array(),
              'training' => array(),
              'workshops' => array()),
          'Energy Executives Program' => array(),
          'internship program' => array(
              'Research Participant Program' => array()),
          'Junior Solar Sprint' => array(),
          'Science Bowl' => array(),
          'Solar Decathlon' => array(
              'Solar Tour of Homes' => array()),
          'Sunrayce' => array(
              'RT: American Solar Challenge' => array()),
          'Sunshot' => array(),
          'visitors' => array()),
      'geothermal energy' => array(
          'heating and cooling' => array(
              'district heating' => array(),
              'domestic hot water' => array(),
              'geothermal heat pump' => array(
                  'geoexchange heat pumps' => array(),
                  'GHP' => array(),
                  'ground source heat pump' => array()),
              'space heating' => array()),
          'power generation' => array(
              'condensers' => array(),
              'direct contact condensers' => array(
                  'DCCs' => array(),
                  'structured packings' => array()),
              'enhanced geothermal system' => array(
                  'EGS' => array(),
                  'hot dry rock' => array()),
              'heat exchangers' => array()),
          'sources' => array(
              'geysers' => array(),
              'hot springs' => array(),
              'volcanoes' => array())),
      'NREL Campus' => array(
          'aerials' => array(),
          'facilities' => array(
              'Alternative Fuel Users Facility' => array(
                  'AFUF' => array()),
              'Building 15' => array(),
              'Building 16' => array(),
              'Building 17' => array(),
              'construction' => array(),
              'Denver West' => array(),
              'East Gate Entrance' => array(),
              'Energy Systems Integration Facility' => array(
                  'ESIF' => array(),
                  'Research Electrical Distribution Bus UF: REDB' => array(),
                  'Supervisory Control and Data Acquisition System UF: SCADA' => array()),
              'Field Test Laboratory Building' => array(
                  'FTLB' => array()),
              'Green Data Center' => array(),
              'High-Flux Solar Furnace' => array(
                  'HFSF' => array()),
              'Integrated Biorefinery Research Facility' => array(
                  'IBRF' => array()),
              'NREL Maintenance Building' => array(),
              'NREL Parking Garage' => array(),
              'NREL Shipping and Receiving' => array(),
              'NREL Site Entrance Building' => array(),
              'NREL Surface Parking' => array(),
              'NREL Visitor Center' => array(),
              'Outdoor Test Facility' => array(
                  'OTF' => array()),
              'Renewable Fuel Heat Plant' => array(
                  'RFHP' => array()),
              'Renewable Fuels and Lubricants Laboratory' => array(
                  'ReFUEL' => array()),
              'Research Support Facility' => array(
                  'RSF' => array()),
              'RSF Visitor Lot' => array(),
              'Science and Technology Facility' => array(
                  'S&TF' => array()),
              'Solar Energy Research Facility' => array(
                  'SERF' => array()),
              'Solar Industrial Mesa Test Area' => array(
                  'SIMTA' => array()),
              'Solar Radiation Research Laboratory' => array(
                  'SRRL' => array()),
              'South Table Mountain Campus',
              'Thermal Test Facility' => array(
                  'TTF' => array()),
              'Thermochemical Users Facility' => array(
                  'TCUF' => array()),
              'Vehicle Testing and Integration Facility' => array(
                  'VTIF' => array()),
              'West Gate Entrance' => array()),
          'historical' => array(),
          'plants and animals' => array(
              'animals' => array(
                  'wildlife' => array()),
              'plants' => array()),
          'staff' => array(
              'directors' => array(),
              'portraits' => array())),
      'solar energy' => array(
          'passive' => array(
              'atrium' => array(),
              'daylighting' => array(),
              'skylights' => array(),
              'space heating' => array(),
              'sunspaces' => array()),
          'photovoltaics' => array(
              'amorphous silicon' => array(),
              'building-applied photovoltaics' => array(
                  'BAPV' => array()),
              'cadmium telluride' => array(),
              'charge controllers' => array(),
              'close-space sublimation systems' => array(),
              'concentrated photovoltaics' => array(
                  'CPV' => array()),
              'copper indium gallium selenide' => array(
                  'CIGS' => array(),
                  'copper indium gallium diselenide' => array()),
              'copper indium selenide' => array(
                  'copper indium diselenide' => array()),
              'gallium arsenide' => array(),
              'hot-wire chemical vapor deposition' => array(),
              'Indo-U.S. Cooperative Photovoltaic Project' => array(),
              'metalorganic chemical vapor deposition' => array(
                  'MOCVD' => array()),
              'metalorganic vapor phase epitaxy' => array(
                  'MOVPE' => array()),
              'microcrystalline' => array(),
              'molecular beam epitaxy' => array(
                  'MBE' => array()),
              'National Center for Photovoltaics' => array(
                  'NCPV' => array()),
              'Photovoltaic Manufacturing Technology Project' => array(
                  'PVMaT' => array()),
              'photovoltaic modules' => array(),
              'physical vapor deposition' => array(),
              'polycrystalline' => array(),
              'power inverters' => array(),
              'Pulsed laser deposition' => array(),
              'PV' => array(),
              'silicon crystals' => array(),
              'solar cells' => array(),
              'solar panel' => array(
                  'solar module' => array()),
              'solar shingles' => array(
                  'photovoltaic shingles' => array()),
              'solar trackers' => array(),
              'thermophotovoltaic' => array(),
              'thin films' => array(),
              'wafers' => array()),
          'radiation' => array(
              'Atmospheric Radiation Measurement Program' => array(
                  'ARM' => array()),
              'photometers' => array(),
              'pyranometers' => array(),
              'pyrgeometers' => array(),
              'pyrheliometers' => array(),
              'radiometers' => array()),
          'thermal' => array(
              'compact linear Fresnel reflectors' => array(),
              'concentrating solar power' => array(),
              'concentrators' => array(),
              'dish collectors' => array(),
              'flat plate collectors' => array(),
              'heat exchangers' => array(),
              'heliostats' => array(),
              'optical furnace' => array(),
              'parabolic mirrors' => array(),
              'parabolic trough collectors' => array(),
              'parabolic troughs' => array(),
              'physical vapor deposition' => array(),
              'receivers' => array(),
              'solar cookers' => array(),
              'solar furnace' => array(),
              'solar power tower' => array(),
              'solar thermal collectors' => array(),
              'solar trackers' => array())),
      'sustainability' => array(
          'energy efficiency' => array(
              'bicycles' => array(),
              'cogeneration' => array(
                  'RT: combined heat and power' => array()),
              'combined heat and power' => array(
                  'CHP' => array(),
                  'RT: cogeneration' => array()),
              'energy audits' => array(
                  'energy analysis' => array()),
              'Energy Star' => array(),
              'Federal Energy Management Program' => array(
                  'FEMP' => array()),
              'fluorescents' => array(),
              'light-emitting diodes' => array(
                  'LEDs' => array()),
              'Motor Challenge' => array(),
              'Rebuilding America' => array(),
              'reverse osmosis' => array(),
              'short-term energy monitoring' => array(
                  'STEM' => array()),
              'space heating' => array(),
              'transit on demand' => array(),
              'vacuum insulation' => array(),
              'zero energy homes' => array(
                  'ZEH' => array())),
          'environment' => array(
              'air pollution' => array(
                  'RT: pollution' => array()),
              'air quality' => array(),
              'bridges' => array(),
              'brown clouds' => array(),
              'clouds' => array(),
              'contamination' => array(),
              'dams' => array(),
              'electromagnetic fields' => array(
                  'EMF' => array()),
              'forests' => array(),
              'greenhouse gas emissions' => array(),
              'hazardous waste' => array(),
              'lakes and rivers' => array(
                  'lakes' => array(),
                  'rivers' => array()),
              'oceans' => array(),
              'pollution' => array(
                  'RT: air pollution' => array()),
              'roads and highways' => array(
                  'highways' => array(),
                  'roads' => array(),
                  'streets' => array()),
              'traffic' => array(),
              'trees' => array()),
          'recycling and waste management' => array(
              'ash' => array(),
              'biodegradable' => array(),
              'bioremediation' => array(),
              'cardboard' => array(),
              'carpet' => array(),
              'compost' => array(),
              'detoxification' => array(),
              'digesters' => array(),
              'garbage' => array(
                  'trash' => array()),
              'landfills' => array(),
              'methane' => array(
                  'RT: biofuels' => array()),
              'newspapers' => array(),
              'sewage treatment' => array(),
              'solid waste' => array(),
              'waste-to-energy' => array(),
              'wastewater' => array(),
              'water treatment plants' => array())),
      'vehicles' => array(
          'Alternative Fuel Vehicles' => array(
              'AFV' => array(),
              'fueling stations' => array(),
              'heavy duty' => array(
                  'buses' => array(),
                  'commercial trucks' => array(),
                  'earth-movers' => array(),
                  'flexible fuel vehicles' => array(
                      'FFV' => array(),
                      'flex-fuel vehicles' => array()),
                  'hybrid electric vehicle' => array(
                      'HEV' => array()),
                  'mass transit' => array(),
                  'methanol' => array(
                      'RT: biofuels' => array()),
                  'plug-in hybrid electric vehicle' => array(
                      'PHEV' => array()),
                  'refuse haulers' => array(),
                  'snow plows' => array(),
                  'tractors' => array(),
                  'ultra-low emission vehicles' => array(
                      'ULEV' => array())),
              'light duty' => array(
                  'cars' => array(),
                  'carts' => array(),
                  'flexible fuel vehicles' => array(
                      'FFV' => array(),
                      'flex-fuel vehicles' => array()),
                  'hybrid electric vehicle' => array(
                      'HEV' => array()),
                  'light-duty trucks' => array(),
                  'methanol' => array(
                      'RT: biofuels' => array()),
                  'minivans' => array(),
                  'pickup trucks' => array(),
                  'plug-in hybrid electric vehicle' => array(
                      'PHEV' => array()),
                  'taxis' => array(),
                  'ultra-low emission vehicles' => array(
                      'ULEV' => array()),
                  'vans' => array())),
          'Clean Cities' => array(
              'electric and hybrid electric' => array(
                  'heavy duty' => array(
                      'buses' => array(),
                      'commercial trucks' => array(),
                      'earth-movers' => array(),
                      'flexible fuel vehicles' => array(
                          'FFV' => array(),
                          'flex-fuel vehicles' => array()),
                      'hybrid electric vehicle' => array(
                          'HEV' => array()),
                      'mass transit' => array(),
                      'methanol' => array(
                          'RT: biofuels' => array()),
                      'plug-in hybrid electric vehicle' => array(
                          'PHEV' => array()),
                      'refuse haulers',
                      'snow plows' => array(),
                      'tractors' => array(),
                      'ultra-low emission vehicles' => array(
                          'ULEV' => array())),
                  'light duty' => array(
                      'cars' => array(),
                      'carts' => array(),
                      'flexible fuel vehicles' => array(
                          'FFV' => array(),
                          'flex-fuel vehicles' => array()),
                      'hybrid electric vehicle' => array(
                          'HEV' => array()),
                      'light-duty trucks' => array(),
                      'methanol' => array(
                          'RT: biofuels' => array()),
                      'minivans' => array(),
                      'pickup trucks' => array(),
                      'plug-in hybrid electric vehicle' => array(
                          'PHEV' => array()),
                      'taxis' => array(),
                      'ultra-low emission vehicles' => array(
                          'ULEV' => array()),
                      'vans' => array())),
              'vehicle related research' => array(
                  'Advanced Automotive Manikin' => array(
                      'ADAM' => array()),
                  'emissions testing' => array()))),
      'videos' => array(
          'b-roll' => array()),
      'water power' => array(
          'hydropower' => array(
              'diversion' => array(),
              'hydroelectric dams' => array(),
              'hydroelectricity' => array(),
              'impoundment' => array(),
              'pumped storage' => array()),
          'marine and hydrokinetic' => array(
              'current energy' => array(),
              'kinetic hydropower systems' => array(
                  'hydrokinetic turbines' => array(),
                  'KHPS' => array()),
              'MHK' => array(),
              'ocean thermal energy conversion' => array(
                  'OTEC' => array()),
              'wave energy' => array())),
      'wind energy' => array(
          'components' => array(
              'accelerometers' => array(),
              'airfoils' => array(),
              'anemometers' => array(),
              'blade testing' => array(),
              'blades' => array(),
              'drive trains' => array(),
              'fatigue testing' => array(),
              'free yaw' => array(),
              'Gearbox Reliability Collaborative' => array(),
              'nacelles' => array(),
              'power inverters' => array(),
              'rotors' => array(),
              'unsteady aerodynamic events' => array(
                  'unsteady aerodynamic experiments' => array()),
              'yaw drive' => array(),
              'yaw system' => array()),
          'distributed wind' => array(
              'wind farms' => array()),
          'National Wind Technology Center' => array(
              'aerials' => array(),
              'NWTC' => array()),
          'offshore' => array(
              'wind farms' => array()),
          'small wind' => array(
              'wind farms' => array(),
              'windmills' => array()),
          'utility scale' => array(
              'wind farms' => array()),
          'vertical-axis wind turbines' => array(
              'VAWT' => array())));

  TermBuild::communications_term_create('structured_keywords', $tags);
}
