<?php

/**
 * @file
 * Contains dam_media_entity_image.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dam_media_entity_image_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dam_media_entity_image module.
    case 'help.page.dam_media_entity_image':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Media Entity Extras.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function dam_media_entity_image_theme() {
  return [
    'dam_media_entity_image' => [
      'render element' => 'children',
    ],
  ];
}
