# @see Configuration schema/metadata at https://drupal.org/node/1905070
# @todo review configuration schema for the value
field.dam_media_serial.value:
  type: sequence
  label: 'Default value'
  sequence:
    - type: mapping
      label: 'Default'
      mapping:
        value:
          type: integer
          label: 'Value'

field.formatter.settings.dam_media_serial_default_formatter:
  type: mapping
  label: 'DAM Media Serial default settings'
  mapping:
    title:
      type: label
      label: 'DAM Media Serial default'

#field.widget.settings.serial_default_widget:
#  type: mapping
#  label: 'Serial default settings'
#  mapping:
#    placeholder:
#      type: label
#      label: 'Placeholder'
