<?php

/**
 * @file
 * Contains dam_elastic_search.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dam_elastic_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dam_elastic_search module.
    case 'help.page.dam_elastic_search':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('DAM Elasticsearch Connector') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function dam_elastic_search_theme() {
  return [
    'dam_elastic_search' => [
      'render element' => 'children',
    ],
  ];
}
